FROM ubuntu:latest
RUN apt-get -y update && \
    apt-get -y install python-pip && \
    pip install --upgrade pip && \
    apt-get -y install zip

COPY . /src
WORKDIR /src

RUN rm -rf vendor/* && \
    rm -rf .git && \
    rm -rf .idea && \
    find . -name \*.pyc -delete

RUN ./requirements.sh
